server:
  port: 8082
  contextPath:  /device
  tomcat:
    basedir:  /home/

spring:
  datasource:
    initialSize:  2
    minIdle:  30
    maxActive:  80
    maxWait:  60000
    timeBetweenEvictionRunsMillis:  60000
    minEvictableIdleTimeMillis: 300000
    validationQuery:  SELECT 'x'
    testWhileIdle:  true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize:  20
    filters:  wall,stat

    ds1:
      driverClassName:  com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/device_ms
      username: root
      password: 123456

    ds2:
      driverClassName:  com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/test2
      username: root
      password: 123456

    ds3:
      driverClassName:  com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/test3
      username: root
      password: 123456

  jpa:
    showSql:  true

  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
    static-path-pattern: /static/**

mybatis:
  mapper-locations: /mappers/**.xml
  config-location:  /mybatis-config.xml