server:
  port: 80
  tomcat:
    basedir:  /home/

spring:
  datasource:
    initialSize:  2
    minIdle:  30
    maxActive:  80
    maxWait:  60000
    timeBetweenEvictionRunsMillis:  60000
    minEvictableIdleTimeMillis: 300000
    validationQuery:  SELECT 'x'
    testWhileIdle:  true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize:  20
    filters:  wall,stat

    ds1:
      driverClassName:  com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/test
      username: root
      password: 123456

    ds2:
      driverClassName:  com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/test2
      username: root
      password: 123456

    ds3:
      driverClassName:  com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/test3
      username: root
      password: 123456

  jpa:
    showSql:  true

  mvc:
    favicon:
      enabled:  false
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
    static-path-pattern: /static/**

  #file
  http:
    multipart:
      max-file-size:  50MB
      max-request-size: 50MB

  mail:
    host: smtp.163.com
    username: 18309225600@163.com
    password: Aa792197389
    default-encoding: utf-8

mail:
  fromMail:
    addr: 18309225600@163.com

mybatis:
  mapper-locations: /mappers/**.xml
  config-location:  /mybatis-config.xml