#端口
server:
  port: 8082
  tomcat:   #这个是一个服务器临时目录  如果不配置这个  默认linux下是一个temp目录   linux会定时清理这个目录  会导致服务出现问题
    basedir:  /home/

#这儿是关于spring的配置  datasource是数据源的配置 下面这一片都是关于数据源的配置
spring:
  datasource:
    initialSize:  2
    minIdle:  30
    maxActive:  80
    maxWait:  60000
    timeBetweenEvictionRunsMillis:  60000
    minEvictableIdleTimeMillis: 300000
    validationQuery:  SELECT 'x'
    testWhileIdle:  true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize:  20
    filters:  wall,stat

    #这个是主数据源   其他俩数据源没用   项目用不到多数据源  我集成的时候集成的是多数据源  所以修改这一个就够了
    ds1:
      driverClassName:  com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/device_ms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 8008208820

    ds2:
      driverClassName:  com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456

    ds3:
      driverClassName:  com.mysql.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/test3?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456

  jpa:
    showSql:  true

  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
    static-path-pattern: /static/**


  #file
  http:
    multipart:
      max-file-size:  50MB
      max-request-size: 50MB

  mail:
    host: smtp.163.com
    username: 18309225600@163.com
    password: Aa792197389
    default-encoding: utf-8

mail:
  fromMail:
    addr: 18309225600@163.com

mybatis:
  mapper-locations: /mappers/**.xml
  config-location:  /mybatis-config.xml